# Render Blueprint spec for deploying the FastAPI backend
# Docs: https://render.com/docs/infrastructure-as-code

services:
  - type: web
    name: cfg-evals-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: MOCK_MODE
        value: "true" # set to false in dashboard if you configure real services
      # Provide your OpenAI key in Render dashboard (mark as secret)
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-5
      # Optional ClickHouse connectivity (set via dashboard or edit here)
      - key: CLICKHOUSE_HOST
        sync: false
      - key: CLICKHOUSE_PORT
        sync: false
      - key: CLICKHOUSE_DATABASE
        sync: false
      - key: CLICKHOUSE_USER
        sync: false
      - key: CLICKHOUSE_PASSWORD
        sync: false
      - key: CLICKHOUSE_SECURE
        sync: false
      - key: CLICKHOUSE_CA_CERT
        sync: false
# Optional: add a static site for the React client later
#  - type: web
#    name: cfg-evals-client
#    env: static
#    buildCommand: cd client && npm install && npm run build
#    staticPublishPath: client/build
#    routes:
#      - type: rewrite
#        source: /?(.*)
#        destination: /index.html
